### PR TITLE
Revert "dom0: esssential: use shared linux firmware"

### PR DESCRIPTION
**Pull request by lifupan**
This reverts commit f8091aecadbf32b33cf5a2facf5902d5eacf0d54.

Even though the systemd-modules-load.service had been disabled
in essential, but the udev would trigge to load kernel modules, too.
Thus the firmwares should be kept in essential instead of in dom0,
otherwise, some kernel moduels will be loaded in essential but failed
to load the firmwares, such as iwlwifi module failed to load
the firmware iwlwifi-7260-17.ucode.

### CODE REVIEW

**Comment by zeddii** [comment]
unfortunately, this cannot merge.

We were about to be designed out of several deployments due to the size of essential. Firmware is absolutely massive and also needs to be independently upgradeable from a read only essential.

As such, this needs to stay.

There are several directions we can take:

 - The system is not usable until dom0 started, so all udev and firmware loading can be explicitly restricted to it.
 - We can explicitly trigger a single firmware load from dom0.
 - If firmware is needed for early boot (but we don't really do NFS boot, so I don't see why), it needs to be built into the initramfs
 - The installer can take a configuration value for a single file to install from dom0 into essential, i.e. like the old shared directories. That way at install time, an image that really, really needs this firmware in essential could make a copy.

But the entire firmware blob is not going back into essential.

**Comment by lifupan** [comment]
Hi, Bruce
The first option was not reasonable, since the dom0's rootfs existed on another disk partition exported as a labe, which needed the udev to trigger, thus we cannot limit the udev after dom0's start;
Second option, since the wifi module had been loaded in essential, thus dom0 would not load the module again, thus it would not load the firmware too. Yes, we can explicitly rm the module and reload the module again, but we can forecast what other firmwares needed in the future. This was only a workaround, not a fix.
Third, if we built the firmware into initramfs, we also need to built the kernel modules into initramfs. Thus we would make the initramfs much more bigger with much more firmware/modules needed on other boards.
Fourth, yes, we can put the needed specific firmware into essential by installer, but the same issue existed too: what about the other firmware needed? How to maintain the upgrading/updating of these firmwares? 

Pulsar 2017 is planed to release tomorrow, so can you help fix this issue as soon as possible? 

Thanks!

Fupan

**Comment by zeddii** [comment]
Yes, leave this with myself/marka. This was an expected outcome of the firmware movement. We will address it post GA, but we do need to go with the smaller essential as part of the new configuration.

**Comment by masselstine** [comment]
I anticipate(d) that there will  be 2 types of FW which will potentially need special handling. The first being FW for drives, such as RAID arrays. The second being Wifi devices.

If you look at the first case, drive related FW, we will need to build dedicated initramfs regardless of FW handling. Specifically the FW is needed before mount.target. So even if we went so far as to move the FW back to -essential we have to design around the FW and kernel module needs of the disk/raid controller.

In the second case, Wifi, there are other binding that result in Wifi not being useable until after we pass mount.target. ie. we require files from disk beyond the FW blob such as wifi settings, wpasupplicant and more. Since in all sane system designs we are not going to be controlling the Wifi from -essential but either dom0 or another container we should always have the required FW blob available since dom0 will be up and running and the firmware-sync complete.

So as you can see the position of the FW is really not a concern (and actually for anything but the first boot is is absolutely moot). For your Wifi case I would suggest the the wifi module be blacklisted and the container which is completing the wifi setup should complete the modprobe. For disk/raid controllers we will need to have a comprehensive solution for the initramfs/module/FW which includes how to uprev/update and is complete dissociated with the FW location.

The above is a bit "handwavy" and needs to be followed up with practical experience. But the design included thought to these scenarios and we hope to be able to put into practice solutions as they are needed. Can we look at the above suggested approach for the Wifi?

**Pull request closed without merging**
