### PR TITLE
Fixes for the read-only root name space

### PR DESCRIPTION
**Pull request by jwessel**
Tested with and without:
echo 'OVERC_ESSENTIAL_MODE="read-only"' >> conf/local.conf

### CODE REVIEW

**Comment by zeddii** [comment]
It seems like this is not based off the OverC meta-oci branch.

i.e.: linux-yocto.inc: Trust the BSP instead

I can do the cherry picks, but this prevents me from merging directly.

**Comment by jwessel** [comment]
It might have been off an older version.  I'll rebase and add another patch in just a bit.

**Comment by jwessel** [comment]
The other patch isn't ready yet, so we can go with what already works.  We are down to just 4 patches.

**Comment by zeddii** [comment]
staged. in testing now.

**Comment by zeddii** [comment]
merged

**Pull request closed without merging**
